/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Ingreso;

import entity.Login;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class Consultar_Usuario extends javax.swing.JDialog {

    /**
     * Creates new form Contraseña_Olvidadaa
     */
    char car;
    private String tipo;

    public Consultar_Usuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tipo = "";
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPral = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        btncontinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/icono.png")).getImage());
        setResizable(false);

        pnlPral.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbltitulo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("Consultar Usuario");

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblusuario.setText("Usuario");

        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuarioKeyTyped(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar 18x18 b y n.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btncontinuar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btncontinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/continuar 18x18 b y n.png"))); // NOI18N
        btncontinuar.setText("Continuar");
        btncontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPralLayout = new javax.swing.GroupLayout(pnlPral);
        pnlPral.setLayout(pnlPralLayout);
        pnlPralLayout.setHorizontalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btncontinuar)
                        .addGap(24, 24, 24)
                        .addComponent(btncancelar))
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addComponent(lblusuario)
                        .addGap(51, 51, 51)
                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbltitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlPralLayout.setVerticalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addGap(23, 23, 23)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusuario)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar)
                    .addComponent(btncontinuar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btncontinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontinuarActionPerformed
        // TODO add your handling code here:
        if (txtusuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor diligenciar el usuario para realizar la consulta.");
            txtusuario.requestFocus();
        } else {
            String usuario = txtusuario.getText();
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
            EntityManager em = emf.createEntityManager();
            EntityTransaction et = em.getTransaction();
            switch (tipo) {
                case "Cambio Contraseña": {
                    Login login = em.find(Login.class, usuario);
                    if (login == null) {
                        JOptionPane.showMessageDialog(null, "Usuario incorrecto.");
                        txtusuario.setText("");
                        txtusuario.requestFocus();
                    } else {
                        Nueva_Contraseña nueva_contraseña = new Nueva_Contraseña(null, rootPaneCheckingEnabled);
                        nueva_contraseña.txtusuario.setText(txtusuario.getText());
                        nueva_contraseña.pswcontraseñanueva.requestFocus();
                        nueva_contraseña.setLogin(login);
                        dispose();
                        nueva_contraseña.setVisible(true);
                    }
                    break;
                }
                case "Cambio Pregunta": {
                    Login login = em.find(Login.class, usuario);
                    if (login == null) {
                        JOptionPane.showMessageDialog(null, "Usuario incorrecto.");
                        txtusuario.setText("");
                        txtusuario.requestFocus();
                    } else {
                        Cambio_Pregunta_Respuesta cambio_pregunta = new Cambio_Pregunta_Respuesta(null, rootPaneCheckingEnabled);
                        cambio_pregunta.txtusuario.setText(txtusuario.getText());
                        cambio_pregunta.cmbpreguntasecreta.requestFocus();
                        dispose();
                        cambio_pregunta.setVisible(true);
                    }
                    break;
                }
                default: {
                    try {
                        Login login = em.find(Login.class, usuario);
                        if (login == null) {
                            JOptionPane.showMessageDialog(null, "Usuario incorrecto.");
                            txtusuario.setText("");
                            txtusuario.requestFocus();
                        } else {
                            Validacion_Respuesta validacion = new Validacion_Respuesta(null, rootPaneCheckingEnabled);
                            switch (login.getPregunta_Secreta()) {
                                case 1: {
                                    validacion.pregunta.setText("Nombre primer mascota");
                                    break;
                                }
                                case 2: {
                                    validacion.pregunta.setText("Nombre Abuela");
                                    break;
                                }
                                case 3: {
                                    validacion.pregunta.setText("Lugar Nacimiento Mamá");
                                    break;
                                }
                            }
                            validacion.setLogin(login);
                            validacion.txtusuario.setText(usuario);
                            validacion.txtrespuesta.requestFocus();
                            dispose();
                            validacion.setVisible(true);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Error: " + e);
                        Logger.getLogger(Consultar_Usuario.class.getName()).log(Level.SEVERE, null, e);
                    } finally {
                        em.close();
                    }
                    break;
                }
            }
        }
    }//GEN-LAST:event_btncontinuarActionPerformed

    private void txtusuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuarioKeyTyped
        // TODO add your handling code here: 
        car = evt.getKeyChar();
        if (car == KeyEvent.VK_ENTER) {
            btncontinuar.doClick();
        }
    }//GEN-LAST:event_txtusuarioKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Consultar_Usuario dialog = new Consultar_Usuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncancelar;
    private javax.swing.JButton btncontinuar;
    public javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel pnlPral;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tipo
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * @param tipo the tipo to set
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
}
