/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Ingreso;

import Clases.Encriptacion;
import entity.Login;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class Nuevo_Usuario extends javax.swing.JDialog {

    /**
     * Creates new form Nuevo_Usuario
     */
    public Nuevo_Usuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPral = new javax.swing.JPanel();
        lbltitulo = new javax.swing.JLabel();
        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblpreguntasecreta = new javax.swing.JLabel();
        cmbpreguntasecreta = new javax.swing.JComboBox<>();
        pswconfirmacioncontraseña = new javax.swing.JPasswordField();
        pswcontraseña = new javax.swing.JPasswordField();
        txtusuario = new javax.swing.JTextField();
        txtrespuesta = new javax.swing.JTextField();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        lblrespuesta = new javax.swing.JLabel();
        lbltipousuario = new javax.swing.JLabel();
        cmbtipousuario = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/icono.png")).getImage());

        pnlPral.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbltitulo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lbltitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitulo.setText("Nuevo Usuario");

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusuario.setText("Usuario");

        lblcontraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcontraseña.setText("Contraseña");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Confirmacion Contraseña");

        lblpreguntasecreta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpreguntasecreta.setText("Pregunta Secreta");

        cmbpreguntasecreta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Nombre primer mascota", "Nombre Abuela", "Lugar de Nacimiento Mamá" }));

        pswconfirmacioncontraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pswcontraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtrespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnaceptar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar 18x18 b y n.png"))); // NOI18N
        btnaceptar.setText("Aceptar");
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar 18x18 b y n.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        lblrespuesta.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblrespuesta.setText("Respuesta");

        lbltipousuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltipousuario.setText("Tipo Usuario");

        cmbtipousuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Usuario", "Administrador" }));

        javax.swing.GroupLayout pnlPralLayout = new javax.swing.GroupLayout(pnlPral);
        pnlPral.setLayout(pnlPralLayout);
        pnlPralLayout.setHorizontalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblusuario)
                            .addComponent(lblcontraseña)
                            .addComponent(lblpreguntasecreta)
                            .addComponent(jLabel1)
                            .addComponent(lblrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltipousuario))
                        .addGap(23, 23, 23)
                        .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswconfirmacioncontraseña)
                            .addComponent(pswcontraseña)
                            .addComponent(txtrespuesta)
                            .addComponent(cmbpreguntasecreta, 0, 161, Short.MAX_VALUE)
                            .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(cmbtipousuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnaceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar))
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lbltitulo)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlPralLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbpreguntasecreta, pswconfirmacioncontraseña, pswcontraseña, txtrespuesta, txtusuario});

        pnlPralLayout.setVerticalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo)
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontraseña)
                    .addComponent(pswcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswconfirmacioncontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpreguntasecreta)
                    .addComponent(cmbpreguntasecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrespuesta))
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipousuario)
                    .addComponent(cmbtipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar)
                    .addComponent(btncancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        // TODO add your handling code here:
        switch (lbltitulo.getText()) {
            case "Nuevo Usuario": {
                String contra1 = new String(pswcontraseña.getPassword());
                String contra2 = new String(pswconfirmacioncontraseña.getPassword());
                if (contra1.equals("") || contra2.equals("") || cmbpreguntasecreta.getSelectedIndex() == 0 || txtrespuesta.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Por favor diligenciar todos los datos");
                    pswcontraseña.requestFocus();
                } else {
                    String contraseña1 = new String(pswcontraseña.getPassword());
                    String contraseña2 = new String(pswconfirmacioncontraseña.getPassword());

                    if (!contraseña1.equals(contraseña2)) {
                        JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
                        pswcontraseña.setText("");
                        pswconfirmacioncontraseña.setText("");
                        pswcontraseña.requestFocus();
                    } else {
                        try {
                            Encriptacion encriptar = new Encriptacion();
                            String usuario = txtusuario.getText();

                            String contraseña;
                            contraseña = encriptar.encriptar(contra1);

                            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
                            EntityManager em = emf.createEntityManager();
                            EntityTransaction et = em.getTransaction();

                            Login login = new Login();
                            login.setUsuario(usuario);
                            login.setContraseña(contraseña);
                            login.setPregunta_Secreta(cmbpreguntasecreta.getSelectedIndex());
                            login.setRespuesta(txtrespuesta.getText());
                            login.setTipo_Usuario(cmbtipousuario.getSelectedItem().toString());

                            et.begin();
                            em.persist(login);
                            et.commit();
                            JOptionPane.showMessageDialog(null, "Usuario creado");
                            dispose();
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, "Error: "+e);
                             Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, e);
                        }
                    }

                }

                break;
            }
            case "Recuperar Contraseña": {

                break;
            }
        }

    }//GEN-LAST:event_btnaceptarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btncancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Nuevo_Usuario dialog = new Nuevo_Usuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnaceptar;
    public javax.swing.JButton btncancelar;
    private javax.swing.JComboBox<String> cmbpreguntasecreta;
    private javax.swing.JComboBox<String> cmbtipousuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblpreguntasecreta;
    private javax.swing.JLabel lblrespuesta;
    private javax.swing.JLabel lbltipousuario;
    public javax.swing.JLabel lbltitulo;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JPanel pnlPral;
    private javax.swing.JPasswordField pswconfirmacioncontraseña;
    public javax.swing.JPasswordField pswcontraseña;
    private javax.swing.JTextField txtrespuesta;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
