/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Vistas.Estudios.Listar_Estudios;
import Vistas.Usuarios.Nuevo_Usuario;
import Vistas.Usuarios.Listar_Usuarios;
import Vistas.Usuarios.Modificar_Usuario;
import Vistas.Usuarios.Eliminar_Usuario;
import Vistas.Egresado.Datos_Egresados;
import Vistas.Egresado.Datos_Egresados_Estudios_Trabajo;
import Vistas.Estudios.Nuevo_Tipo_Estudio;
import Vistas.Estudios.Consultar_Tipo_Estudio;
import Vistas.Ingreso.Cambio_Pregunta_Respuesta;
import Vistas.Ingreso.Consultar_Usuario;
import Vistas.Ingreso.Validacion_Contraseña;
import Vistas.Ingreso.Nueva_Contraseña;
import Vistas.Ingreso.Vista_Login;
import Vistas.Trabajos.Consultar_Tipo_Trabajo;
import Vistas.Trabajos.Listar_Trabajos;
import Vistas.Trabajos.Nuevo_Tipo_Trabajo;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 *
 * @author CRISTIAN
 */
public class Vista_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Princiapl
     */
    private String usuario;

    public Vista_Principal() {
        initComponents();
        usuario = "";
        this.setLocationRelativeTo(null);
    }

    public void centrar(JInternalFrame internalFrame) {
        int x = (pnlescritorio.getWidth()) / 2 - internalFrame.getWidth() / 2;
        int y = (pnlescritorio.getHeight()) / 2 - internalFrame.getHeight() / 2;
        if (internalFrame.isShowing()) {
            internalFrame.setLocation(x, y);
        } else {
            pnlescritorio.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuitemsalir = new javax.swing.JMenuItem();
        mnuEgresados = new javax.swing.JMenu();
        mnuitemegresados = new javax.swing.JMenuItem();
        mnuitemestudiosytrabajos = new javax.swing.JMenuItem();
        mnuEstudios = new javax.swing.JMenu();
        mnuitemnuevoestudio = new javax.swing.JMenuItem();
        mnuitemconsultaestudio = new javax.swing.JMenuItem();
        mnuitemlistarestudios = new javax.swing.JMenuItem();
        mnuTrabajos = new javax.swing.JMenu();
        mnuitemnuevotrabjo = new javax.swing.JMenuItem();
        mnuitemconsultatrabajo = new javax.swing.JMenuItem();
        mnulistartrabajos = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuitemnuevousuario = new javax.swing.JMenuItem();
        mnuitemmodificarusuario = new javax.swing.JMenuItem();
        mnuitemeliminarusuario = new javax.swing.JMenuItem();
        mnuitemlistarusuarios = new javax.swing.JMenuItem();
        mnuConfiguracion = new javax.swing.JMenu();
        mnuitemcambiarcontraseña = new javax.swing.JMenuItem();
        mnuitemcambiarpregunta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/icono.png")).getImage());
        setResizable(false);

        pnlescritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout pnlescritorioLayout = new javax.swing.GroupLayout(pnlescritorio);
        pnlescritorio.setLayout(pnlescritorioLayout);
        pnlescritorioLayout.setHorizontalGroup(
            pnlescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        pnlescritorioLayout.setVerticalGroup(
            pnlescritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mnuitemsalir.setText("Salir");
        mnuitemsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemsalirActionPerformed(evt);
            }
        });
        mnuArchivo.add(mnuitemsalir);

        jMenuBar1.add(mnuArchivo);

        mnuEgresados.setText("Egresados");

        mnuitemegresados.setText("Egresado");
        mnuitemegresados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemegresadosActionPerformed(evt);
            }
        });
        mnuEgresados.add(mnuitemegresados);

        mnuitemestudiosytrabajos.setText("Estudios y Trabajos");
        mnuitemestudiosytrabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemestudiosytrabajosActionPerformed(evt);
            }
        });
        mnuEgresados.add(mnuitemestudiosytrabajos);

        jMenuBar1.add(mnuEgresados);

        mnuEstudios.setText("Estudios");

        mnuitemnuevoestudio.setText("Nuevo Tipo de Estudio");
        mnuitemnuevoestudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemnuevoestudioActionPerformed(evt);
            }
        });
        mnuEstudios.add(mnuitemnuevoestudio);

        mnuitemconsultaestudio.setText("Consultar Tipo de Estudios");
        mnuitemconsultaestudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemconsultaestudioActionPerformed(evt);
            }
        });
        mnuEstudios.add(mnuitemconsultaestudio);

        mnuitemlistarestudios.setText("Listar Estudios");
        mnuitemlistarestudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemlistarestudiosActionPerformed(evt);
            }
        });
        mnuEstudios.add(mnuitemlistarestudios);

        jMenuBar1.add(mnuEstudios);

        mnuTrabajos.setText("Trabajos");

        mnuitemnuevotrabjo.setText("Nuevo Tipo de Trabajo");
        mnuitemnuevotrabjo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemnuevotrabjoActionPerformed(evt);
            }
        });
        mnuTrabajos.add(mnuitemnuevotrabjo);

        mnuitemconsultatrabajo.setText("Consultar Tipo de Trabajo");
        mnuitemconsultatrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemconsultatrabajoActionPerformed(evt);
            }
        });
        mnuTrabajos.add(mnuitemconsultatrabajo);

        mnulistartrabajos.setText("Listar Trabajos");
        mnulistartrabajos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnulistartrabajosActionPerformed(evt);
            }
        });
        mnuTrabajos.add(mnulistartrabajos);

        jMenuBar1.add(mnuTrabajos);

        mnuUsuarios.setText("Usuarios");

        mnuitemnuevousuario.setText("Nuevo Usuario");
        mnuitemnuevousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemnuevousuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuitemnuevousuario);

        mnuitemmodificarusuario.setText("Modificar Usuario");
        mnuitemmodificarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemmodificarusuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuitemmodificarusuario);

        mnuitemeliminarusuario.setText("Eliminar Usuario");
        mnuitemeliminarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemeliminarusuarioActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuitemeliminarusuario);

        mnuitemlistarusuarios.setText("Listar Usuarios");
        mnuitemlistarusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemlistarusuariosActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuitemlistarusuarios);

        jMenuBar1.add(mnuUsuarios);

        mnuConfiguracion.setText("Configuracion");

        mnuitemcambiarcontraseña.setText("Cambiar Contraseña");
        mnuitemcambiarcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemcambiarcontraseñaActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(mnuitemcambiarcontraseña);

        mnuitemcambiarpregunta.setText("Cambiar Pregunta");
        mnuitemcambiarpregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuitemcambiarpreguntaActionPerformed(evt);
            }
        });
        mnuConfiguracion.add(mnuitemcambiarpregunta);

        jMenuBar1.add(mnuConfiguracion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlescritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuitemegresadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemegresadosActionPerformed
        // TODO add your handling code here:
        Datos_Egresados ob = new Datos_Egresados();
        centrar(ob);
    }//GEN-LAST:event_mnuitemegresadosActionPerformed

    private void mnuitemsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemsalirActionPerformed
        // TODO add your handling code here:
        Vista_Login login = new Vista_Login();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_mnuitemsalirActionPerformed

    private void mnuitemcambiarcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemcambiarcontraseñaActionPerformed
        // TODO add your handling code here:
        Validacion_Contraseña validacion = new Validacion_Contraseña(this, rootPaneCheckingEnabled);
        validacion.setUsuario(usuario);
        validacion.pswcontraseñanueva.requestFocus();
        validacion.setVisible(true);
    }//GEN-LAST:event_mnuitemcambiarcontraseñaActionPerformed

    private void mnuitemcambiarpreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemcambiarpreguntaActionPerformed
        // TODO add your handling code here:
        Validacion_Contraseña validacion = new Validacion_Contraseña(this, rootPaneCheckingEnabled);
        validacion.setUsuario(usuario);
        validacion.setTipo("Pregunta");
        validacion.pswcontraseñanueva.requestFocus();
        validacion.setVisible(true);
    }//GEN-LAST:event_mnuitemcambiarpreguntaActionPerformed

    private void mnuitemnuevousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemnuevousuarioActionPerformed
        // TODO add your handling code here:
        Nuevo_Usuario nuevo_usuario = new Nuevo_Usuario();
        centrar(nuevo_usuario);
    }//GEN-LAST:event_mnuitemnuevousuarioActionPerformed

    private void mnuitemmodificarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemmodificarusuarioActionPerformed
        // TODO add your handling code here:
        Modificar_Usuario modificar = new Modificar_Usuario();
        centrar(modificar);
    }//GEN-LAST:event_mnuitemmodificarusuarioActionPerformed

    private void mnuitemlistarusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemlistarusuariosActionPerformed
        // TODO add your handling code here:
        Listar_Usuarios listar = new Listar_Usuarios();
        listar.listar_Usuarios();
        centrar(listar);
    }//GEN-LAST:event_mnuitemlistarusuariosActionPerformed

    private void mnuitemeliminarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemeliminarusuarioActionPerformed
        // TODO add your handling code here:
        Eliminar_Usuario eliminar = new Eliminar_Usuario();
        centrar(eliminar);
    }//GEN-LAST:event_mnuitemeliminarusuarioActionPerformed

    private void mnuitemlistarestudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemlistarestudiosActionPerformed
        // TODO add your handling code here:
        Listar_Estudios estudio = new Listar_Estudios();
        estudio.listar_Estudios();
        centrar(estudio);
    }//GEN-LAST:event_mnuitemlistarestudiosActionPerformed

    private void mnuitemnuevoestudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemnuevoestudioActionPerformed
        // TODO add your handling code here:
        Nuevo_Tipo_Estudio estudio = new Nuevo_Tipo_Estudio();
        estudio.setEstudios(estudio);
        centrar(estudio);
    }//GEN-LAST:event_mnuitemnuevoestudioActionPerformed

    private void mnuitemconsultaestudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemconsultaestudioActionPerformed
        // TODO add your handling code here:
        Consultar_Tipo_Estudio estudio = new Consultar_Tipo_Estudio();
        estudio.setEstudios(estudio);
        centrar(estudio);
    }//GEN-LAST:event_mnuitemconsultaestudioActionPerformed

    private void mnulistartrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnulistartrabajosActionPerformed
        // TODO add your handling code here:
        Listar_Trabajos listar = new Listar_Trabajos();
        listar.listar_Trabajos();
        centrar(listar);
    }//GEN-LAST:event_mnulistartrabajosActionPerformed

    private void mnuitemnuevotrabjoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemnuevotrabjoActionPerformed
        // TODO add your handling code here:
        Nuevo_Tipo_Trabajo trabajo = new Nuevo_Tipo_Trabajo();
        centrar(trabajo);
    }//GEN-LAST:event_mnuitemnuevotrabjoActionPerformed

    private void mnuitemconsultatrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemconsultatrabajoActionPerformed
        // TODO add your handling code here:
        Consultar_Tipo_Trabajo consulta = new Consultar_Tipo_Trabajo();
        consulta.setTrabajos(consulta);
        centrar(consulta);
    }//GEN-LAST:event_mnuitemconsultatrabajoActionPerformed

    private void mnuitemestudiosytrabajosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuitemestudiosytrabajosActionPerformed
        // TODO add your handling code here:
        Datos_Egresados_Estudios_Trabajo estudio_trabajo = new Datos_Egresados_Estudios_Trabajo();
        estudio_trabajo.cargar_Estudios();
        estudio_trabajo.cargar_Trabajos();
        centrar(estudio_trabajo);
    }//GEN-LAST:event_mnuitemestudiosytrabajosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuConfiguracion;
    private javax.swing.JMenu mnuEgresados;
    private javax.swing.JMenu mnuEstudios;
    private javax.swing.JMenu mnuTrabajos;
    public javax.swing.JMenu mnuUsuarios;
    public javax.swing.JMenuItem mnuitemcambiarcontraseña;
    public javax.swing.JMenuItem mnuitemcambiarpregunta;
    private javax.swing.JMenuItem mnuitemconsultaestudio;
    private javax.swing.JMenuItem mnuitemconsultatrabajo;
    public javax.swing.JMenuItem mnuitemegresados;
    private javax.swing.JMenuItem mnuitemeliminarusuario;
    private javax.swing.JMenuItem mnuitemestudiosytrabajos;
    private javax.swing.JMenuItem mnuitemlistarestudios;
    private javax.swing.JMenuItem mnuitemlistarusuarios;
    private javax.swing.JMenuItem mnuitemmodificarusuario;
    private javax.swing.JMenuItem mnuitemnuevoestudio;
    private javax.swing.JMenuItem mnuitemnuevotrabjo;
    private javax.swing.JMenuItem mnuitemnuevousuario;
    public javax.swing.JMenuItem mnuitemsalir;
    private javax.swing.JMenuItem mnulistartrabajos;
    public javax.swing.JDesktopPane pnlescritorio;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the usuario
     */
    public String getUsuario() {
        return usuario;
    }

    /**
     * @param usuario the usuario to set
     */
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
}
