/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Usuarios;

import entity.Login;
import entity.Paises;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CRISTIAN
 */
public class Listar_Usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Listar_Usuarios
     */
    DefaultTableModel model;

    public Listar_Usuarios() {
        initComponents();
    }

    public void listar_Usuarios() {
        
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
        EntityManager em = emf.createEntityManager();
        EntityTransaction et = em.getTransaction();
        try {
            String datos[] = new String[2];
            model = (DefaultTableModel) tblinfousuarios.getModel();
            int cantidad_usuarios = 0, cantidadadministradores = 0;
            TypedQuery<Login> consulta_Usuarios = em.createNamedQuery("Login.findAll", Login.class);
            List<Login> lista = consulta_Usuarios.getResultList();
            for (Login a : lista) {
                datos[0] = a.getUsuario();
                datos[1] = a.getTipo_Usuario();
                switch (a.getTipo_Usuario()) {
                    case "Usuario": {
                        cantidad_usuarios++;
                        break;
                    }
                    case "Administrador": {
                        cantidadadministradores++;
                        break;
                    }
                }

                model.addRow(datos);
            }
            tblinfousuarios.setModel(model);
            txtcantidadusuarios.setText("" + cantidad_usuarios);
            txtcantidadadministradores.setText("" + cantidadadministradores);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
            Logger.getLogger(Listar_Usuarios.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            em.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPral = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblinfousuarios = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            } };
            lblcantidadusuarios = new javax.swing.JLabel();
            txtcantidadusuarios = new javax.swing.JTextField();
            lbladministradores = new javax.swing.JLabel();
            txtcantidadadministradores = new javax.swing.JTextField();
            btnactualizar = new javax.swing.JButton();

            setClosable(true);
            setTitle("LISTADO USUARIOS");

            pnlPral.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

            tblinfousuarios.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Usuario", "Tipo Usuario"
                }
            ));
            jScrollPane1.setViewportView(tblinfousuarios);

            lblcantidadusuarios.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
            lblcantidadusuarios.setText("Usuarios");

            txtcantidadusuarios.setEditable(false);
            txtcantidadusuarios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            txtcantidadusuarios.setHorizontalAlignment(javax.swing.JTextField.CENTER);

            lbladministradores.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
            lbladministradores.setText("Administradores");

            txtcantidadadministradores.setEditable(false);
            txtcantidadadministradores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            txtcantidadadministradores.setHorizontalAlignment(javax.swing.JTextField.CENTER);

            btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/actualizar 24x24 by n.png"))); // NOI18N
            btnactualizar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnactualizarActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout pnlPralLayout = new javax.swing.GroupLayout(pnlPral);
            pnlPral.setLayout(pnlPralLayout);
            pnlPralLayout.setHorizontalGroup(
                pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPralLayout.createSequentialGroup()
                    .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlPralLayout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblcantidadusuarios)
                                .addComponent(lbladministradores))
                            .addGap(18, 18, 18)
                            .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcantidadadministradores, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcantidadusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(btnactualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlPralLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            pnlPralLayout.setVerticalGroup(
                pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlPralLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlPralLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                            .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblcantidadusuarios)
                                .addComponent(txtcantidadusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbladministradores)
                                .addComponent(txtcantidadadministradores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(13, 13, 13))
                        .addGroup(pnlPralLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(btnactualizar)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlPral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < tblinfousuarios.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
        listar_Usuarios();
    }//GEN-LAST:event_btnactualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbladministradores;
    private javax.swing.JLabel lblcantidadusuarios;
    private javax.swing.JPanel pnlPral;
    private javax.swing.JTable tblinfousuarios;
    private javax.swing.JTextField txtcantidadadministradores;
    private javax.swing.JTextField txtcantidadusuarios;
    // End of variables declaration//GEN-END:variables
}
