/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Usuarios;

import Clases.Encriptacion;
import Vistas.Ingreso.Cambio_Pregunta_Respuesta;
import Vistas.Ingreso.Nueva_Contraseña;
import entity.Login;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class Modificar_Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Nuevo_Usuarioo
     */
    char car;
    Login login;

    public Modificar_Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPral = new javax.swing.JPanel();
        lblusuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        lblusuarioc = new javax.swing.JLabel();
        txtusuarioc = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnconsultar = new javax.swing.JButton();
        btnmodificarcontraseña = new javax.swing.JButton();
        btnmodificarpregunta = new javax.swing.JButton();
        btnmodificartipousuario = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbltipousuario = new javax.swing.JLabel();
        cmbtipousuario = new javax.swing.JComboBox<>();
        btncancelar = new javax.swing.JButton();
        btnaceptar = new javax.swing.JButton();
        btnnuevaconsulta = new javax.swing.JButton();

        setClosable(true);
        setTitle("MODIFICACION USUARIO");

        pnlPral.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusuario.setText("Usuario");

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblusuarioc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusuarioc.setText("Usuario");

        txtusuarioc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtusuarioc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuariocKeyTyped(evt);
            }
        });

        btnconsultar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/consultar 24x24 b y n.png"))); // NOI18N
        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btnmodificarcontraseña.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnmodificarcontraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar 18x18 b y n.png"))); // NOI18N
        btnmodificarcontraseña.setText("Modificar Contraseña");
        btnmodificarcontraseña.setEnabled(false);
        btnmodificarcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarcontraseñaActionPerformed(evt);
            }
        });

        btnmodificarpregunta.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnmodificarpregunta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar 18x18 b y n.png"))); // NOI18N
        btnmodificarpregunta.setText("Modificar Pregunta");
        btnmodificarpregunta.setEnabled(false);
        btnmodificarpregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarpreguntaActionPerformed(evt);
            }
        });

        btnmodificartipousuario.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnmodificartipousuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar 18x18 b y n.png"))); // NOI18N
        btnmodificartipousuario.setText("Modificar Tipo Usuario");
        btnmodificartipousuario.setEnabled(false);
        btnmodificartipousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificartipousuarioActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lbltipousuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltipousuario.setText("Tipo Usuario");

        cmbtipousuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Usuario", "Administrador" }));
        cmbtipousuario.setEnabled(false);

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar 18x18 b y n.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnaceptar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar 18x18 b y n.png"))); // NOI18N
        btnaceptar.setText("Aceptar");
        btnaceptar.setEnabled(false);
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(lbltipousuario)
                .addGap(18, 18, 18)
                .addComponent(cmbtipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnaceptar)
                .addGap(18, 18, 18)
                .addComponent(btncancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipousuario)
                    .addComponent(cmbtipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar)
                    .addComponent(btncancelar))
                .addGap(15, 15, 15))
        );

        btnnuevaconsulta.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnnuevaconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuevo 18x18x.png"))); // NOI18N
        btnnuevaconsulta.setText("Nueva Consulta");
        btnnuevaconsulta.setEnabled(false);
        btnnuevaconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevaconsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPralLayout = new javax.swing.GroupLayout(pnlPral);
        pnlPral.setLayout(pnlPralLayout);
        pnlPralLayout.setHorizontalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPralLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblusuarioc)
                .addGap(18, 18, 18)
                .addComponent(txtusuarioc, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnconsultar)
                .addGap(22, 22, 22))
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(lblusuario)
                                .addGap(27, 27, 27)
                                .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnmodificarcontraseña)
                                    .addComponent(btnmodificartipousuario))
                                .addGap(27, 27, 27)
                                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnnuevaconsulta)
                                    .addComponent(btnmodificarpregunta))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlPralLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnmodificarcontraseña, btnmodificarpregunta, btnmodificartipousuario, btnnuevaconsulta});

        pnlPralLayout.setVerticalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuarioc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusuarioc)
                    .addComponent(btnconsultar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusuario))
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodificarcontraseña)
                    .addComponent(btnmodificarpregunta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodificartipousuario)
                    .addComponent(btnnuevaconsulta))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        // TODO add your handling code here:
        if (cmbtipousuario.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor seleccionar Tipo de Usuario");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
            EntityManager em = emf.createEntityManager();
            EntityTransaction et = em.getTransaction();
            try {
                login.setTipo_Usuario(cmbtipousuario.getSelectedItem().toString());
                et.begin();
                em.merge(login);
                et.commit();
                JOptionPane.showMessageDialog(null, "Se ha modificado el tipo de usuario satisfactoriamente.");
                cmbtipousuario.setEnabled(false);
                btnaceptar.setEnabled(false);
                btncancelar.setEnabled(false);
                btnnuevaconsulta.setEnabled(true);
                btnmodificarcontraseña.setEnabled(true);
                btnmodificarpregunta.setEnabled(true);
                btnmodificartipousuario.setEnabled(true);
                btnmodificarcontraseña.requestFocus();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
                Logger.getLogger(Modificar_Usuario.class.getName()).log(Level.SEVERE, null, e);
            } finally {
                em.close();
            }
        }
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        cmbtipousuario.setSelectedItem(login.getTipo_Usuario());
        cmbtipousuario.setEnabled(false);
        btnaceptar.setEnabled(false);
        btncancelar.setEnabled(false);
        btnmodificarcontraseña.setEnabled(true);
        btnmodificarpregunta.setEnabled(true);
        btnmodificartipousuario.setEnabled(true);
        btnnuevaconsulta.setEnabled(true);
        btnmodificarcontraseña.requestFocus();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        if (txtusuarioc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor diligenciar el usuario.");
            txtusuarioc.requestFocus();
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
            EntityManager em = emf.createEntityManager();
            EntityTransaction et = em.getTransaction();
            try {
                login = em.find(Login.class, txtusuarioc.getText());
                if (login == null) {
                    JOptionPane.showMessageDialog(null, "El usuario " + txtusuarioc.getText() + " no existe en la base de datos.");
                    txtusuarioc.setText("");
                    txtusuarioc.requestFocus();
                } else {
                    txtusuario.setText(login.getUsuario());
                    cmbtipousuario.setSelectedItem(login.getTipo_Usuario());
                    txtusuarioc.setText("");
                    txtusuarioc.setEditable(false);
                    btnconsultar.setEnabled(false);
                    btnmodificarcontraseña.setEnabled(true);
                    btnmodificarpregunta.setEnabled(true);
                    btnmodificartipousuario.setEnabled(true);
                    btnnuevaconsulta.setEnabled(true);
                    btnmodificarcontraseña.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
                Logger.getLogger(Modificar_Usuario.class.getName()).log(Level.SEVERE, null, e);
            } finally {
                em.close();
            }
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void txtusuariocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuariocKeyTyped
        // TODO add your handling code here:
        car = evt.getKeyChar();
        if (car == KeyEvent.VK_ENTER) {
            btnconsultar.doClick();
        }
    }//GEN-LAST:event_txtusuariocKeyTyped

    private void btnmodificarcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarcontraseñaActionPerformed
        // TODO add your handling code here:
        Nueva_Contraseña nueva_contraseña = new Nueva_Contraseña(null, rootPaneCheckingEnabled);
        nueva_contraseña.txtusuario.setText(login.getUsuario());
        nueva_contraseña.pswcontraseñanueva.requestFocus();
        nueva_contraseña.setLogin(login);
        nueva_contraseña.setVisible(true);
    }//GEN-LAST:event_btnmodificarcontraseñaActionPerformed

    private void btnmodificarpreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarpreguntaActionPerformed
        // TODO add your handling code here:
        Cambio_Pregunta_Respuesta cambio_pregunta = new Cambio_Pregunta_Respuesta(null, rootPaneCheckingEnabled);
        cambio_pregunta.txtusuario.setText(login.getUsuario());
        cambio_pregunta.cmbpreguntasecreta.requestFocus();
        cambio_pregunta.setVisible(true);
    }//GEN-LAST:event_btnmodificarpreguntaActionPerformed

    private void btnmodificartipousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificartipousuarioActionPerformed
        // TODO add your handling code here:
        cmbtipousuario.setEnabled(true);
        btnaceptar.setEnabled(true);
        btncancelar.setEnabled(true);
        btnmodificarcontraseña.setEnabled(false);
        btnmodificarpregunta.setEnabled(false);
        btnmodificartipousuario.setEnabled(false);
        btnnuevaconsulta.setEnabled(false);
        cmbtipousuario.requestFocus();
    }//GEN-LAST:event_btnmodificartipousuarioActionPerformed

    private void btnnuevaconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevaconsultaActionPerformed
        // TODO add your handling code here:
        txtusuario.setText("");
        cmbtipousuario.setSelectedIndex(0);
        btnmodificarcontraseña.setEnabled(false);
        btnmodificarpregunta.setEnabled(false);
        btnmodificartipousuario.setEnabled(false);
        btnnuevaconsulta.setEnabled(false);
        txtusuarioc.setEditable(true);
        txtusuarioc.requestFocus();
        btnconsultar.setEnabled(true);
    }//GEN-LAST:event_btnnuevaconsultaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnaceptar;
    public javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btnmodificarcontraseña;
    private javax.swing.JButton btnmodificarpregunta;
    private javax.swing.JButton btnmodificartipousuario;
    private javax.swing.JButton btnnuevaconsulta;
    private javax.swing.JComboBox<String> cmbtipousuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbltipousuario;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JLabel lblusuarioc;
    private javax.swing.JPanel pnlPral;
    public javax.swing.JTextField txtusuario;
    public javax.swing.JTextField txtusuarioc;
    // End of variables declaration//GEN-END:variables
}
