/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Usuarios;

import Clases.Encriptacion;
import entity.Login;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class Nuevo_Usuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Nuevo_Usuarioo
     */
    char car;
    private String tipo;

    public Nuevo_Usuario() {
        initComponents();
        tipo = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPral = new javax.swing.JPanel();
        lblusuario = new javax.swing.JLabel();
        lblcontraseña = new javax.swing.JLabel();
        lblconfirmacioncontraseña = new javax.swing.JLabel();
        lblpreguntasecreta = new javax.swing.JLabel();
        cmbpreguntasecreta = new javax.swing.JComboBox<>();
        pswconfirmacioncontraseña = new javax.swing.JPasswordField();
        pswcontraseña = new javax.swing.JPasswordField();
        txtusuario = new javax.swing.JTextField();
        txtrespuesta = new javax.swing.JTextField();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        lblrespuesta = new javax.swing.JLabel();
        lbltipousuario = new javax.swing.JLabel();
        cmbtipousuario = new javax.swing.JComboBox<>();
        lblusuarioc = new javax.swing.JLabel();
        txtusuarioc = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnconsultar = new javax.swing.JButton();

        setClosable(true);
        setTitle("NUEVO USUARIO");

        pnlPral.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusuario.setText("Usuario");

        lblcontraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblcontraseña.setText("Contraseña");

        lblconfirmacioncontraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblconfirmacioncontraseña.setText("Confirmacion Contraseña");

        lblpreguntasecreta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblpreguntasecreta.setText("Pregunta Secreta");

        cmbpreguntasecreta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Nombre primer mascota", "Nombre Abuela", "Lugar de Nacimiento Mamá" }));
        cmbpreguntasecreta.setEnabled(false);

        pswconfirmacioncontraseña.setEditable(false);
        pswconfirmacioncontraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pswcontraseña.setEditable(false);
        pswcontraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtusuario.setEditable(false);
        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtrespuesta.setEditable(false);
        txtrespuesta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnaceptar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar 18x18 b y n.png"))); // NOI18N
        btnaceptar.setText("Aceptar");
        btnaceptar.setEnabled(false);
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar 18x18 b y n.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        lblrespuesta.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblrespuesta.setText("Respuesta");

        lbltipousuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbltipousuario.setText("Tipo Usuario");

        cmbtipousuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Usuario", "Administrador" }));
        cmbtipousuario.setEnabled(false);

        lblusuarioc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblusuarioc.setText("Usuario");

        txtusuarioc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtusuarioc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuariocKeyTyped(evt);
            }
        });

        btnconsultar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/consultar 24x24 b y n.png"))); // NOI18N
        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPralLayout = new javax.swing.GroupLayout(pnlPral);
        pnlPral.setLayout(pnlPralLayout);
        pnlPralLayout.setHorizontalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblusuario)
                                    .addComponent(lblcontraseña)
                                    .addComponent(lblpreguntasecreta)
                                    .addComponent(lblconfirmacioncontraseña)
                                    .addComponent(lblrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbltipousuario))
                                .addGap(23, 23, 23)
                                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pswconfirmacioncontraseña)
                                    .addComponent(pswcontraseña)
                                    .addComponent(txtrespuesta)
                                    .addComponent(cmbpreguntasecreta, 0, 170, Short.MAX_VALUE)
                                    .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(cmbtipousuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(btnaceptar)
                                .addGap(18, 18, 18)
                                .addComponent(btncancelar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPralLayout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(lblusuarioc)
                .addGap(18, 18, 18)
                .addComponent(txtusuarioc, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnconsultar)
                .addGap(22, 22, 22))
        );
        pnlPralLayout.setVerticalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuarioc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblusuarioc)
                    .addComponent(btnconsultar))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblusuario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtusuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcontraseña)
                    .addComponent(pswcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswconfirmacioncontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblconfirmacioncontraseña))
                .addGap(14, 14, 14)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpreguntasecreta)
                    .addComponent(cmbpreguntasecreta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtrespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblrespuesta))
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipousuario)
                    .addComponent(cmbtipousuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar)
                    .addComponent(btncancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        // TODO add your handling code here:

        String contra1 = new String(pswcontraseña.getPassword());
        String contra2 = new String(pswconfirmacioncontraseña.getPassword());
        if (contra1.equals("") || contra2.equals("") || cmbpreguntasecreta.getSelectedIndex() == 0 || txtrespuesta.getText().equals("") || cmbtipousuario.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor diligenciar todos los datos");
            pswcontraseña.requestFocus();
        } else {
            String contraseña1 = new String(pswcontraseña.getPassword());
            String contraseña2 = new String(pswconfirmacioncontraseña.getPassword());

            if (!contraseña1.equals(contraseña2)) {
                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden.");
                pswcontraseña.setText("");
                pswconfirmacioncontraseña.setText("");
                pswcontraseña.requestFocus();
            } else {
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
                EntityManager em = emf.createEntityManager();
                EntityTransaction et = em.getTransaction();
                try {
                    Encriptacion encriptar = new Encriptacion();
                    String usuario = txtusuario.getText();

                    String contraseña;
                    contraseña = encriptar.encriptar(contra1);

                    Login login = new Login();
                    login.setUsuario(usuario);
                    login.setContraseña(contraseña);
                    login.setPregunta_Secreta(cmbpreguntasecreta.getSelectedIndex());
                    login.setRespuesta(txtrespuesta.getText());
                    login.setTipo_Usuario(cmbtipousuario.getSelectedItem().toString());

                    et.begin();
                    em.persist(login);
                    et.commit();
                    JOptionPane.showMessageDialog(null, "El Usuario ha sido creado con satisfacción.");
                    dispose();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error: " + e);
                    Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, e);
                } finally {
                    em.close();
                }
            }
        }
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        txtusuarioc.setEditable(true);
        btnconsultar.setEnabled(true);
        txtusuario.setText("");
        pswcontraseña.setText("");
        pswconfirmacioncontraseña.setText("");
        cmbpreguntasecreta.setSelectedIndex(0);
        txtrespuesta.setText("");
        cmbtipousuario.setSelectedIndex(0);
        pswcontraseña.setEditable(false);
        pswconfirmacioncontraseña.setEditable(false);
        txtrespuesta.setEditable(false);
        cmbpreguntasecreta.setEnabled(false);
        cmbtipousuario.setEnabled(false);
        btnaceptar.setEnabled(false);
        btncancelar.setEnabled(false);
        txtusuarioc.requestFocus();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        if (txtusuarioc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor diligenciar el usuario.");
            txtusuarioc.requestFocus();
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
            EntityManager em = emf.createEntityManager();
            EntityTransaction et = em.getTransaction();
            try {
                Login login = em.find(Login.class, txtusuarioc.getText());
                if (login == null) {
                    txtusuario.setText(txtusuarioc.getText());
                    txtusuarioc.setText("");
                    txtusuarioc.setEditable(false);
                    btnconsultar.setEnabled(false);
                    pswcontraseña.setEditable(true);
                    pswconfirmacioncontraseña.setEditable(true);
                    cmbpreguntasecreta.setEnabled(true);
                    txtrespuesta.setEditable(true);
                    cmbtipousuario.setEnabled(true);
                    btnaceptar.setEnabled(true);
                    btncancelar.setEnabled(true);
                    pswcontraseña.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "El usuario " + txtusuarioc.getText() + " ya existe en la base de datos.");
                    txtusuarioc.setText("");
                    txtusuarioc.requestFocus();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
                Logger.getLogger(Nuevo_Usuario.class.getName()).log(Level.SEVERE, null, e);
            } finally {
                em.close();
            }
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void txtusuariocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuariocKeyTyped
        // TODO add your handling code here:
        car = evt.getKeyChar();
        if (car == KeyEvent.VK_ENTER) {
            btnconsultar.doClick();
        }
    }//GEN-LAST:event_txtusuariocKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnaceptar;
    public javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JComboBox<String> cmbpreguntasecreta;
    private javax.swing.JComboBox<String> cmbtipousuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblconfirmacioncontraseña;
    private javax.swing.JLabel lblcontraseña;
    private javax.swing.JLabel lblpreguntasecreta;
    private javax.swing.JLabel lblrespuesta;
    private javax.swing.JLabel lbltipousuario;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JLabel lblusuarioc;
    private javax.swing.JPanel pnlPral;
    private javax.swing.JPasswordField pswconfirmacioncontraseña;
    public javax.swing.JPasswordField pswcontraseña;
    private javax.swing.JTextField txtrespuesta;
    public javax.swing.JTextField txtusuario;
    public javax.swing.JTextField txtusuarioc;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the tipo
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * @param tipo the tipo to set
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
}
