/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Egresado;

import entity.Egresados;
import entity.Egresados_Estudios;
import entity.Egresados_Trabajos;
import entity.Estudios;
import entity.Trabajos;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class Datos_Egresados_Estudios_Trabajo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista_Egresados_Estudios_Trabajo
     */
    public Datos_Egresados_Estudios_Trabajo() {
        initComponents();

    }

    public void cargar_Estudios() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
        EntityManager em = emf.createEntityManager();
        EntityTransaction et = em.getTransaction();
        try {
            TypedQuery<Estudios> consulta_Estudios = em.createNamedQuery("Estudios.findAll", Estudios.class);
            List<Estudios> lista_Estudios = consulta_Estudios.getResultList();
            for (Estudios a : lista_Estudios) {
                cmbtipoestudio.addItem(a.getTipoEstudio());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
            Logger.getLogger(Datos_Egresados_Estudios_Trabajo.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            em.close();
        }
    }

    public void cargar_Trabajos() {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
        EntityManager em = emf.createEntityManager();
        EntityTransaction et = em.getTransaction();
        try {
            TypedQuery<Trabajos> consulta_Trabajos = em.createNamedQuery("Trabajos.findAll", Trabajos.class);
            List<Trabajos> lista_Trabajos = consulta_Trabajos.getResultList();
            for (Trabajos a : lista_Trabajos) {
                cmbtipotrabajo.addItem(a.getNombreTrabajo());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
            Logger.getLogger(Datos_Egresados_Estudios_Trabajo.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            em.close();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupobotonesestudio = new javax.swing.ButtonGroup();
        grupobotonestrabaja = new javax.swing.ButtonGroup();
        pnlPral = new javax.swing.JPanel();
        pnlConsulta = new javax.swing.JPanel();
        lblidegresadoc = new javax.swing.JLabel();
        txtidegresadoc = new javax.swing.JTextField();
        btnconsultar = new javax.swing.JButton();
        pnlSecundario = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        btnmodificar = new javax.swing.JButton();
        btnnuevaconsulta = new javax.swing.JButton();
        pnlAceptar = new javax.swing.JPanel();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        lblmensaje = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlDatos = new javax.swing.JPanel();
        lblestudios = new javax.swing.JLabel();
        lblfacultad = new javax.swing.JLabel();
        lblcarrera = new javax.swing.JLabel();
        cmbfacultad = new javax.swing.JComboBox();
        cmbcarreras = new javax.swing.JComboBox();
        lblsituacionactual = new javax.swing.JLabel();
        lblestudio = new javax.swing.JLabel();
        lbltipoestudio = new javax.swing.JLabel();
        lbltrabajo = new javax.swing.JLabel();
        lbltipotrabajo = new javax.swing.JLabel();
        cmbtipotrabajo = new javax.swing.JComboBox();
        btnnotrabajo = new javax.swing.JRadioButton();
        btnsitrabajo = new javax.swing.JRadioButton();
        cmbtipoestudio = new javax.swing.JComboBox();
        btnsiestudio = new javax.swing.JRadioButton();
        btnnoestudio = new javax.swing.JRadioButton();
        lbldatospersonales = new javax.swing.JLabel();
        lblidegresado = new javax.swing.JLabel();
        txtidegresado = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        lblnombre = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        cmbtipodocumento = new javax.swing.JComboBox();
        lbltipodocumento = new javax.swing.JLabel();

        setClosable(true);
        setTitle("ESTUDIO Y TRABAJO");

        pnlPral.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        pnlConsulta.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblidegresadoc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblidegresadoc.setText("ID");

        txtidegresadoc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnconsultar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/consultar 24x24 b y n.png"))); // NOI18N
        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultaLayout = new javax.swing.GroupLayout(pnlConsulta);
        pnlConsulta.setLayout(pnlConsultaLayout);
        pnlConsultaLayout.setHorizontalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblidegresadoc)
                .addGap(18, 18, 18)
                .addComponent(txtidegresadoc, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnconsultar)
                .addGap(31, 31, 31))
        );
        pnlConsultaLayout.setVerticalGroup(
            pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidegresadoc)
                    .addComponent(txtidegresadoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconsultar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlSecundario.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        pnlBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btnmodificar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/modificar 18x18 b y n.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setEnabled(false);
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btnnuevaconsulta.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnnuevaconsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuevo 18x18x.png"))); // NOI18N
        btnnuevaconsulta.setText("Nueva Consulta");
        btnnuevaconsulta.setEnabled(false);
        btnnuevaconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevaconsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnmodificar)
                .addGap(18, 18, 18)
                .addComponent(btnnuevaconsulta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmodificar)
                    .addComponent(btnnuevaconsulta))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pnlAceptar.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        btnaceptar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar 18x18 b y n.png"))); // NOI18N
        btnaceptar.setText("Aceptar");
        btnaceptar.setEnabled(false);
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar 18x18 b y n.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setEnabled(false);

        lblmensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblmensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmensaje.setText("Estado");

        javax.swing.GroupLayout pnlAceptarLayout = new javax.swing.GroupLayout(pnlAceptar);
        pnlAceptar.setLayout(pnlAceptarLayout);
        pnlAceptarLayout.setHorizontalGroup(
            pnlAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAceptarLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(pnlAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblmensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlAceptarLayout.createSequentialGroup()
                        .addComponent(btnaceptar)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAceptarLayout.setVerticalGroup(
            pnlAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAceptarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblmensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAceptarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar)
                    .addComponent(btncancelar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblestudios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblestudios.setText("Estudios");

        lblfacultad.setText("Facultad");

        lblcarrera.setText("Carrera");

        cmbfacultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        cmbfacultad.setEnabled(false);

        cmbcarreras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        cmbcarreras.setEnabled(false);

        lblsituacionactual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblsituacionactual.setText("Situacion Actual");

        lblestudio.setText("¿Estudia?");

        lbltipoestudio.setText("Tipo de Estudio");

        lbltrabajo.setText("¿Trabaja?");

        lbltipotrabajo.setText("Tipo de Trabajo");

        cmbtipotrabajo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        cmbtipotrabajo.setEnabled(false);

        grupobotonestrabaja.add(btnnotrabajo);
        btnnotrabajo.setSelected(true);
        btnnotrabajo.setText("No");
        btnnotrabajo.setEnabled(false);
        btnnotrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnotrabajoActionPerformed(evt);
            }
        });

        grupobotonestrabaja.add(btnsitrabajo);
        btnsitrabajo.setText("Si");
        btnsitrabajo.setEnabled(false);
        btnsitrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsitrabajoActionPerformed(evt);
            }
        });

        cmbtipoestudio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione..." }));
        cmbtipoestudio.setEnabled(false);

        grupobotonesestudio.add(btnsiestudio);
        btnsiestudio.setText("Si");
        btnsiestudio.setEnabled(false);
        btnsiestudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiestudioActionPerformed(evt);
            }
        });

        grupobotonesestudio.add(btnnoestudio);
        btnnoestudio.setSelected(true);
        btnnoestudio.setText("No");
        btnnoestudio.setEnabled(false);
        btnnoestudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoestudioActionPerformed(evt);
            }
        });

        lbldatospersonales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbldatospersonales.setText("Datos Personales");

        lblidegresado.setText("ID");

        txtidegresado.setEditable(false);

        txtnombre.setEditable(false);

        lblnombre.setText("Nombre");

        lblapellido.setText("Apellido");

        txtapellido.setEditable(false);

        cmbtipodocumento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "CEDULA", "TARJETA IDENTIDAD", "PASAPORTE" }));
        cmbtipodocumento.setEnabled(false);

        lbltipodocumento.setText("Tipo Documento");

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblidegresado)
                            .addComponent(lblapellido))
                        .addGap(61, 61, 61)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidegresado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblnombre)
                    .addComponent(lbldatospersonales)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addComponent(lblestudio)
                        .addGap(51, 51, 51)
                        .addComponent(btnsiestudio)
                        .addGap(18, 18, 18)
                        .addComponent(btnnoestudio))
                    .addComponent(lblsituacionactual)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltrabajo)
                            .addComponent(lbltipotrabajo))
                        .addGap(25, 25, 25)
                        .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDatosLayout.createSequentialGroup()
                                .addComponent(btnsitrabajo)
                                .addGap(18, 18, 18)
                                .addComponent(btnnotrabajo))
                            .addComponent(cmbtipotrabajo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lbltipodocumento)
                    .addComponent(lblcarrera)
                    .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cmbtipoestudio, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDatosLayout.createSequentialGroup()
                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblfacultad)
                                .addComponent(lblestudios)
                                .addComponent(lbltipoestudio))
                            .addGap(25, 25, 25)
                            .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbcarreras, 0, 182, Short.MAX_VALUE)
                                .addComponent(cmbfacultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(0, 78, Short.MAX_VALUE))
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbldatospersonales)
                .addGap(29, 29, 29)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblidegresado)
                    .addComponent(txtidegresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipodocumento)
                    .addComponent(cmbtipodocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblapellido)
                    .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lblestudios)
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfacultad)
                    .addComponent(cmbfacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcarrera)
                    .addComponent(cmbcarreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lblsituacionactual)
                .addGap(27, 27, 27)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblestudio)
                    .addComponent(btnnoestudio)
                    .addComponent(btnsiestudio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipoestudio)
                    .addComponent(cmbtipoestudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltrabajo)
                    .addComponent(btnsitrabajo)
                    .addComponent(btnnotrabajo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltipotrabajo)
                    .addComponent(cmbtipotrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pnlDatos);

        javax.swing.GroupLayout pnlSecundarioLayout = new javax.swing.GroupLayout(pnlSecundario);
        pnlSecundario.setLayout(pnlSecundarioLayout);
        pnlSecundarioLayout.setHorizontalGroup(
            pnlSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAceptar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        pnlSecundarioLayout.setVerticalGroup(
            pnlSecundarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecundarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlPralLayout = new javax.swing.GroupLayout(pnlPral);
        pnlPral.setLayout(pnlPralLayout);
        pnlPralLayout.setHorizontalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPralLayout.setVerticalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSecundario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        if (btnsiestudio.isSelected()) {
            cmbtipoestudio.setEnabled(true);
        }
        if (btnsitrabajo.isSelected()) {
            cmbtipotrabajo.setEnabled(true);
        }

        btnsiestudio.setEnabled(true);
        btnnoestudio.setEnabled(true);
        btnsitrabajo.setEnabled(true);
        btnnotrabajo.setEnabled(true);

        btnaceptar.setEnabled(true);
        btncancelar.setEnabled(true);

        btnmodificar.setEnabled(false);
        btnnuevaconsulta.setEnabled(false);


    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        // TODO add your handling code here:
        if (btnsiestudio.isSelected() && cmbtipoestudio.getSelectedIndex() == 0 || btnsitrabajo.isSelected() && cmbtipotrabajo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Por favor diligenciar completamente los datos.");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
            EntityManager em = emf.createEntityManager();
            EntityTransaction et = em.getTransaction();
            try {
                int id_egresado = Integer.parseInt(txtidegresado.getText());
                int codigo_estudio = 0, codigo_trabajo = 0;

                Egresados_Estudios egresado_estudios = em.find(Egresados_Estudios.class, id_egresado);
                if (btnnoestudio.isSelected()) {
                    if (egresado_estudios == null) {
                    } else {
                        et.begin();
                        em.remove(egresado_estudios);
                        et.commit();
                    }
                }

                Egresados_Trabajos egresado_trabajos = em.find(Egresados_Trabajos.class, id_egresado);
                if (btnnotrabajo.isSelected()) {
                    if (egresado_trabajos == null) {
                    } else {
                        et.begin();
                        em.remove(egresado_trabajos);
                        et.commit();
                    }
                }

                if (btnsiestudio.isSelected()) {
                    TypedQuery<Estudios> consulta_Estudios = em.createNamedQuery("consulta_e", Estudios.class);
                    consulta_Estudios.setParameter("nombre", cmbtipoestudio.getSelectedItem().toString());
                    List<Estudios> lista_Estudios = consulta_Estudios.getResultList();
                    for (Estudios a : lista_Estudios) {
                        codigo_estudio = a.getCodigoEstudio();
                    }
                    if (egresado_estudios == null) {
                        egresado_estudios = new Egresados_Estudios();
                        egresado_estudios.setId_Egresado(id_egresado);
                        egresado_estudios.setCodigo_Estudio(codigo_estudio);
                        et.begin();
                        em.persist(egresado_estudios);
                        et.commit();
                    } else {
                        egresado_estudios.setCodigo_Estudio(codigo_estudio);
                        et.begin();
                        em.merge(egresado_estudios);
                        et.commit();
                    }
                }
                if (btnsitrabajo.isSelected()) {
                    TypedQuery<Trabajos> consulta_Trabajos = em.createNamedQuery("consulta_t", Trabajos.class);
                    consulta_Trabajos.setParameter("nombre", cmbtipotrabajo.getSelectedItem().toString());
                    List<Trabajos> lista_Trabajos = consulta_Trabajos.getResultList();
                    for (Trabajos a : lista_Trabajos) {
                        codigo_trabajo = a.getCodigoTrabajo();
                    }

                    if (egresado_trabajos == null) {
                        egresado_trabajos = new Egresados_Trabajos();
                        egresado_trabajos.setId_Egresado(id_egresado);
                        egresado_trabajos.setCodigo_Trabajo(codigo_trabajo);
                        et.begin();
                        em.persist(egresado_trabajos);
                        et.commit();
                    } else {
                        egresado_trabajos.setCodigo_Trabajo(codigo_trabajo);
                        et.begin();
                        em.merge(egresado_trabajos);
                        et.commit();
                    }
                }

                JOptionPane.showMessageDialog(null, "Los datos se han actualizado correctamente.");

                cmbtipoestudio.setEnabled(false);
                cmbtipotrabajo.setEnabled(false);
                btnsiestudio.setEnabled(false);
                btnnoestudio.setEnabled(false);
                btnsitrabajo.setEnabled(false);
                btnnotrabajo.setEnabled(false);

                btnaceptar.setEnabled(false);
                btncancelar.setEnabled(false);

                btnmodificar.setEnabled(true);
                btnnuevaconsulta.setEnabled(true);
                btnmodificar.requestFocus();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
                Logger.getLogger(Datos_Egresados_Estudios_Trabajo.class.getName()).log(Level.SEVERE, null, e);
            } finally {
                em.close();
            }

        }
    }//GEN-LAST:event_btnaceptarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
        EntityManager em = emf.createEntityManager();
        EntityTransaction et = em.getTransaction();
        if (txtidegresadoc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor diligenciar el Id del egresado para realizar la consulta");
            txtidegresadoc.requestFocus();
        } else {
            try {
                int id_egresado = Integer.parseInt(txtidegresadoc.getText());
                Egresados egresados = em.find(Egresados.class, id_egresado);
                if (egresados == null) {
                    JOptionPane.showMessageDialog(null, "No hay ningun egresado con el ID " + id_egresado + "\n"
                            + "Para crear un nuevo egresado dirigase al Menu Egresados/Egresado");
                } else {
                    txtidegresado.setText(Integer.toString(egresados.getId_Egresado()));
                    cmbtipodocumento.setSelectedItem(egresados.getTipo_Documento());
                    txtnombre.setText(egresados.getPrimer_Nombre() + " " + egresados.getSegundo_Nombre());
                    txtapellido.setText(egresados.getPrimer_Apellido() + " " + egresados.getSegundo_Apellido());
                    btnmodificar.setEnabled(true);
                    btnnuevaconsulta.setEnabled(true);

                    txtidegresadoc.setText("");
                    txtidegresadoc.setEditable(false);
                    btnconsultar.setEnabled(false);
                    btnmodificar.requestFocus();
                    Egresados_Estudios egresado_estudios = em.find(Egresados_Estudios.class, id_egresado);
                    if (egresado_estudios == null) {
                        btnnoestudio.setSelected(true);
                    } else {
                        btnsiestudio.setSelected(true);
                        Estudios estudios = em.find(Estudios.class, egresado_estudios.getCodigo_Estudio());
                        cmbtipoestudio.setSelectedItem(estudios.getTipoEstudio());
                    }
                    Egresados_Trabajos egresado_trabajos = em.find(Egresados_Trabajos.class, id_egresado);
                    if (egresado_trabajos == null) {
                        btnnotrabajo.setSelected(true);
                    } else {
                        btnsitrabajo.setSelected(true);
                        Trabajos trabajos = em.find(Trabajos.class, egresado_trabajos.getCodigo_Trabajo());
                        cmbtipotrabajo.setSelectedItem(trabajos.getNombreTrabajo());
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
                Logger.getLogger(Datos_Egresados_Estudios_Trabajo.class.getName()).log(Level.SEVERE, null, e);
            } finally {
                em.close();
            }
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btnsiestudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiestudioActionPerformed
        // TODO add your handling code here:
        cmbtipoestudio.setEnabled(true);
    }//GEN-LAST:event_btnsiestudioActionPerformed

    private void btnsitrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsitrabajoActionPerformed
        // TODO add your handling code here:
        cmbtipotrabajo.setEnabled(true);
    }//GEN-LAST:event_btnsitrabajoActionPerformed

    private void btnnotrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnotrabajoActionPerformed
        // TODO add your handling code here:
        cmbtipotrabajo.setSelectedIndex(0);
        cmbtipotrabajo.setEnabled(false);
    }//GEN-LAST:event_btnnotrabajoActionPerformed

    private void btnnoestudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoestudioActionPerformed
        // TODO add your handling code here:
        cmbtipoestudio.setSelectedIndex(0);
        cmbtipoestudio.setEnabled(false);
    }//GEN-LAST:event_btnnoestudioActionPerformed

    private void btnnuevaconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevaconsultaActionPerformed
        // TODO add your handling code here:
        txtidegresado.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        cmbtipodocumento.setSelectedIndex(0);
        cmbcarreras.setSelectedIndex(0);
        cmbfacultad.setSelectedIndex(0);
        cmbtipoestudio.setSelectedIndex(0);
        cmbtipotrabajo.setSelectedIndex(0);
        btnnoestudio.setSelected(true);
        btnnotrabajo.setSelected(true);
        btnmodificar.setEnabled(false);
        btnnuevaconsulta.setEnabled(false);
        
        txtidegresadoc.setEditable(true);
        btnconsultar.setEnabled(true);
        txtidegresadoc.requestFocus();
    }//GEN-LAST:event_btnnuevaconsultaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnaceptar;
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btnconsultar;
    public javax.swing.JButton btnmodificar;
    public javax.swing.JRadioButton btnnoestudio;
    public javax.swing.JRadioButton btnnotrabajo;
    public javax.swing.JButton btnnuevaconsulta;
    public javax.swing.JRadioButton btnsiestudio;
    public javax.swing.JRadioButton btnsitrabajo;
    public javax.swing.JComboBox cmbcarreras;
    public javax.swing.JComboBox cmbfacultad;
    public javax.swing.JComboBox cmbtipodocumento;
    public javax.swing.JComboBox cmbtipoestudio;
    public javax.swing.JComboBox cmbtipotrabajo;
    private javax.swing.ButtonGroup grupobotonesestudio;
    private javax.swing.ButtonGroup grupobotonestrabaja;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblcarrera;
    private javax.swing.JLabel lbldatospersonales;
    private javax.swing.JLabel lblestudio;
    private javax.swing.JLabel lblestudios;
    private javax.swing.JLabel lblfacultad;
    private javax.swing.JLabel lblidegresado;
    private javax.swing.JLabel lblidegresadoc;
    public javax.swing.JLabel lblmensaje;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblsituacionactual;
    private javax.swing.JLabel lbltipodocumento;
    private javax.swing.JLabel lbltipoestudio;
    private javax.swing.JLabel lbltipotrabajo;
    private javax.swing.JLabel lbltrabajo;
    private javax.swing.JPanel pnlAceptar;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlConsulta;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlPral;
    private javax.swing.JPanel pnlSecundario;
    public javax.swing.JTextField txtapellido;
    public javax.swing.JTextField txtidegresado;
    public javax.swing.JTextField txtidegresadoc;
    public javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
