/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Estudios;

import entity.Estudios;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class Nuevo_Tipo_Estudio extends javax.swing.JInternalFrame {

    /**
     * Creates new form Nuevo_Tipo_Estudio
     */
    private Nuevo_Tipo_Estudio estudios_v;

    public Nuevo_Tipo_Estudio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPral = new javax.swing.JPanel();
        lnlnombreestudioc = new javax.swing.JLabel();
        txtnombreestudioc = new javax.swing.JTextField();
        btnconsultar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblcodigoestudio = new javax.swing.JLabel();
        lblnombreestudio = new javax.swing.JLabel();
        txtcodigoestudio = new javax.swing.JTextField();
        txtnombreestudio = new javax.swing.JTextField();
        btnaceptar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("NUEVO TIPO ESTUDIO");

        pnlPral.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lnlnombreestudioc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lnlnombreestudioc.setText("Nombre");

        txtnombreestudioc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnconsultar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/consultar 24x24 b y n.png"))); // NOI18N
        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        lblcodigoestudio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblcodigoestudio.setText("Codigo");

        lblnombreestudio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblnombreestudio.setText("Nombre");

        txtcodigoestudio.setEditable(false);
        txtcodigoestudio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        txtnombreestudio.setEditable(false);
        txtnombreestudio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnaceptar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnaceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar 18x18 b y n.png"))); // NOI18N
        btnaceptar.setText("Aceptar");
        btnaceptar.setEnabled(false);
        btnaceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar 18x18 b y n.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPralLayout = new javax.swing.GroupLayout(pnlPral);
        pnlPral.setLayout(pnlPralLayout);
        pnlPralLayout.setHorizontalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lnlnombreestudioc)
                                .addGap(18, 18, 18)
                                .addComponent(txtnombreestudioc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnconsultar))
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnaceptar)
                                .addGap(31, 31, 31)
                                .addComponent(btncancelar))
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcodigoestudio)
                                    .addComponent(lblnombreestudio))
                                .addGap(23, 23, 23)
                                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnombreestudio)
                                    .addComponent(txtcodigoestudio, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPralLayout.setVerticalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnlnombreestudioc)
                    .addComponent(txtnombreestudioc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigoestudio)
                    .addComponent(txtcodigoestudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombreestudio)
                    .addComponent(txtnombreestudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar)
                    .addComponent(btncancelar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptarActionPerformed
        // TODO add your handling code here:
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
        EntityManager em = emf.createEntityManager();
        EntityTransaction et = em.getTransaction();
        try {
            Estudios estudio = new Estudios();
            estudio.setCodigoEstudio(Integer.parseInt(txtcodigoestudio.getText()));
            estudio.setTipoEstudio(txtnombreestudio.getText());
            et.begin();
            em.persist(estudio);
            et.commit();
            JOptionPane.showMessageDialog(null, "El Tipo de Estudio con el nombre " + txtnombreestudio.getText() + " ha sido creado con satisfacción.");
            txtcodigoestudio.setText("");
            txtnombreestudio.setText("");
            btnaceptar.setEnabled(false);
            btncancelar.setEnabled(false);
            txtnombreestudioc.setEditable(true);
            btnconsultar.setEnabled(true);
            txtnombreestudioc.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
            Logger.getLogger(Nuevo_Tipo_Estudio.class.getName()).log(Level.SEVERE, null, e);
        } finally {
            em.close();
        }

    }//GEN-LAST:event_btnaceptarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        if (txtnombreestudioc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor diligenciar el nombre del Tipo de Estudio para realizar la consulta.");
            txtnombreestudioc.requestFocus();
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
            EntityManager em = emf.createEntityManager();
            EntityTransaction et = em.getTransaction();
            try {
                TypedQuery<Estudios> consulta_Usuarios = em.createNamedQuery("consulta_e", Estudios.class);
                consulta_Usuarios.setParameter("nombre", txtnombreestudioc.getText());
                List<Estudios> lista = consulta_Usuarios.getResultList();
                if (lista.size() > 0) {
                    JOptionPane.showMessageDialog(null, "El Tipo de Estudio con nombre " + txtnombreestudioc.getText() + " ya existe en la base de datos");
                    txtnombreestudioc.setText("");
                    txtnombreestudioc.requestFocus();
                } else if (lista.size() == 0) {
                    int seleccion = JOptionPane.showOptionDialog(
                            null,
                            "No existe un Tipo de Estudio con el nombre de " + txtnombreestudioc.getText() + "\n"
                            + "¿Desea crear uno con este nombre?",
                            "Selector de opciones",
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null, // null para icono por defecto.
                            new Object[]{"SI", "NO",}, // null para YES, NO y CANCEL
                            "opcion 1");
                    if (seleccion == 0) {
                        consulta_Usuarios = em.createNamedQuery("Estudios.findAll", Estudios.class);
                        lista = consulta_Usuarios.getResultList();
                        txtcodigoestudio.setText("" + (lista.size() + 1));
                        txtnombreestudio.setText(txtnombreestudioc.getText());
                        btnaceptar.setEnabled(true);
                        btncancelar.setEnabled(true);
                        btnconsultar.setEnabled(false);
                        txtnombreestudioc.setText("");
                        txtnombreestudioc.setEditable(false);
                        btnaceptar.requestFocus();
                    } else if (seleccion == 1) {
                        txtnombreestudioc.setText("");
                        txtnombreestudioc.requestFocus();
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
                Logger.getLogger(Nuevo_Tipo_Estudio.class.getName()).log(Level.SEVERE, null, e);
            } finally {
                em.close();
            }

        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        txtcodigoestudio.setText("");
        txtnombreestudio.setText("");
        btnaceptar.setEnabled(false);
        btncancelar.setEnabled(false);
        txtnombreestudioc.setEditable(true);
        btnconsultar.setEnabled(true);
        txtnombreestudioc.requestFocus();
    }//GEN-LAST:event_btncancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblcodigoestudio;
    private javax.swing.JLabel lblnombreestudio;
    private javax.swing.JLabel lnlnombreestudioc;
    private javax.swing.JPanel pnlPral;
    private javax.swing.JTextField txtcodigoestudio;
    private javax.swing.JTextField txtnombreestudio;
    private javax.swing.JTextField txtnombreestudioc;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the estudios
     */
    public Nuevo_Tipo_Estudio getEstudios() {
        return estudios_v;
    }

    /**
     * @param estudios the estudios to set
     */
    public void setEstudios(Nuevo_Tipo_Estudio estudios_v) {
        this.estudios_v = estudios_v;
    }
}
