/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Trabajos;

import Vistas.Trabajos.*;
import entity.Trabajos;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import javax.persistence.TypedQuery;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class Nuevo_Tipo_Trabajo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Nuevo_Tipo_Estudio
     */
    private Nuevo_Tipo_Trabajo trabajos_v;

    public Nuevo_Tipo_Trabajo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPral = new javax.swing.JPanel();
        lblnombretrabajoc = new javax.swing.JLabel();
        txtnombretrabajoc = new javax.swing.JTextField();
        btnconsultar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblcodigotrabajo = new javax.swing.JLabel();
        lblnombretrabajo = new javax.swing.JLabel();
        txtcodigotrabajo = new javax.swing.JTextField();
        txtnombretrabajo = new javax.swing.JTextField();
        btnacetar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("NUEVO TIPO DE TRABAJO");

        pnlPral.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        lblnombretrabajoc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblnombretrabajoc.setText("Nombre");

        txtnombretrabajoc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnconsultar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnconsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/consultar 24x24 b y n.png"))); // NOI18N
        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        lblcodigotrabajo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblcodigotrabajo.setText("Codigo");

        lblnombretrabajo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lblnombretrabajo.setText("Nombre");

        txtcodigotrabajo.setEditable(false);
        txtcodigotrabajo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        txtnombretrabajo.setEditable(false);
        txtnombretrabajo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        btnacetar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnacetar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aceptar 18x18 b y n.png"))); // NOI18N
        btnacetar.setText("Aceptar");
        btnacetar.setEnabled(false);
        btnacetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacetarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cancelar 18x18 b y n.png"))); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.setEnabled(false);
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPralLayout = new javax.swing.GroupLayout(pnlPral);
        pnlPral.setLayout(pnlPralLayout);
        pnlPralLayout.setHorizontalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(pnlPralLayout.createSequentialGroup()
                        .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lblnombretrabajoc)
                                .addGap(18, 18, 18)
                                .addComponent(txtnombretrabajoc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnconsultar))
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnacetar)
                                .addGap(31, 31, 31)
                                .addComponent(btncancelar))
                            .addGroup(pnlPralLayout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcodigotrabajo)
                                    .addComponent(lblnombretrabajo))
                                .addGap(23, 23, 23)
                                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnombretrabajo)
                                    .addComponent(txtcodigotrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 7, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPralLayout.setVerticalGroup(
            pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPralLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombretrabajoc)
                    .addComponent(txtnombretrabajoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigotrabajo)
                    .addComponent(txtcodigotrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombretrabajo)
                    .addComponent(txtnombretrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlPralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnacetar)
                    .addComponent(btncancelar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnacetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacetarActionPerformed
        // TODO add your handling code here:
     
                EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
                EntityManager em = emf.createEntityManager();
                EntityTransaction et = em.getTransaction();
                try {
                    Trabajos trabajo = new Trabajos();
                    trabajo.setCodigoTrabajo(Integer.parseInt(txtcodigotrabajo.getText()));
                    trabajo.setNombreTrabajo(txtnombretrabajo.getText());
                    et.begin();
                    em.persist(trabajo);
                    et.commit();
                    JOptionPane.showMessageDialog(null, "El Tipo de Trabajo con el nombre " + txtnombretrabajo.getText() + " ha sido creado con satisfacción.");
                    txtcodigotrabajo.setText("");
                    txtnombretrabajo.setText("");
                    btnacetar.setEnabled(false);
                    btncancelar.setEnabled(false);
                    txtnombretrabajoc.setEditable(true);
                    btnconsultar.setEnabled(true);
                    txtnombretrabajoc.requestFocus();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error: " + e);
                    Logger.getLogger(Nuevo_Tipo_Trabajo.class.getName()).log(Level.SEVERE, null, e);
                } finally {
                    em.close();
                }
    }//GEN-LAST:event_btnacetarActionPerformed

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        if (txtnombretrabajoc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor diligenciar el nombre del Tipo de Trabajo para realizar la consulta.");
            txtnombretrabajoc.requestFocus();
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("Control_Egresados_JPAPU");
            EntityManager em = emf.createEntityManager();
            EntityTransaction et = em.getTransaction();
            try {
                TypedQuery<Trabajos> consulta_Trabajos = em.createNamedQuery("consulta_t", Trabajos.class);
                consulta_Trabajos.setParameter("nombre", txtnombretrabajoc.getText());
                List<Trabajos> lista = consulta_Trabajos.getResultList();
                if (lista.size() > 0) {
                    JOptionPane.showMessageDialog(null, "El Tipo de Trabajo con nombre " + txtnombretrabajoc.getText() + " ya existe en la base de datos");
                    txtnombretrabajoc.setText("");
                    txtnombretrabajoc.requestFocus();
                } else if (lista.size() == 0) {
                    int seleccion = JOptionPane.showOptionDialog(
                            null,
                            "No existe un Tipo de Trabajo con el nombre de " + txtnombretrabajoc.getText() + "\n"
                            + "¿Desea crear uno con este nombre?",
                            "Selector de opciones",
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null, // null para icono por defecto.
                            new Object[]{"SI", "NO",}, // null para YES, NO y CANCEL
                            "opcion 1");
                    if (seleccion == 0) {
                        consulta_Trabajos = em.createNamedQuery("Trabajos.findAll", Trabajos.class);
                        lista = consulta_Trabajos.getResultList();
                        txtcodigotrabajo.setText("" + (lista.size() + 1));
                        txtnombretrabajo.setText(txtnombretrabajoc.getText());
                        btnacetar.setEnabled(true);
                        btncancelar.setEnabled(true);
                        btnconsultar.setEnabled(false);
                        txtnombretrabajoc.setText("");
                        txtnombretrabajoc.setEditable(false);
                        btnacetar.requestFocus();
                    } else if (seleccion == 1) {
                        txtnombretrabajoc.setText("");
                        txtnombretrabajoc.requestFocus();
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
                Logger.getLogger(Nuevo_Tipo_Trabajo.class.getName()).log(Level.SEVERE, null, e);
            } finally {
                em.close();
            }
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        txtcodigotrabajo.setText("");
        txtnombretrabajo.setText("");
        btnacetar.setEnabled(false);
        btncancelar.setEnabled(false);
        txtnombretrabajoc.setEditable(true);
        btnconsultar.setEnabled(true);
        txtnombretrabajoc.requestFocus();
    }//GEN-LAST:event_btncancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacetar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblcodigotrabajo;
    private javax.swing.JLabel lblnombretrabajo;
    private javax.swing.JLabel lblnombretrabajoc;
    private javax.swing.JPanel pnlPral;
    private javax.swing.JTextField txtcodigotrabajo;
    private javax.swing.JTextField txtnombretrabajo;
    private javax.swing.JTextField txtnombretrabajoc;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the estudios
     */
    public Nuevo_Tipo_Trabajo getTrabajos() {
        return trabajos_v;
    }

    /**
     * @param estudios the estudios to set
     */
    public void setTrabajos(Nuevo_Tipo_Trabajo trabajos_v) {
        this.trabajos_v = trabajos_v;
    }
}
